CREATE DATABASE SysB;
Use SysB;


CREATE TABLE TB_CATEGORIAS(
idCategoria INT IDENTITY(1,1) NOT NULL,
nome VARCHAR(100) NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY (idCategoria)
);



CREATE TABLE TB_FORNECEDORES(
idFornecedor INT IDENTITY(1,1) NOT NULL,
nome VARCHAR(100) NOT NULL,
cnpj VARCHAR(15) NOT NULL UNIQUE,
telefone VARCHAR(11) NOT NULL,
dtContrato DATE NOT NULL,
ativo bit DEFAULT 1,
CONSTRAINT PK_FORNECEDOR PRIMARY KEY (idFornecedor)
);

CREATE TABLE TB_PRODUTOS (
idProduto INT IDENTITY(1,1) NOT NULL,
idCategoria INT NOT NULL,
idFornecedor INT NOT NULL,
nome VARCHAR(100) NOT NULL,
descricao varchar(255) NOT NULL,
valor DEC(10,2) NOT NULL,
codigoDeBarra VARCHAR(255) NOT NULL,
Marca varchar(100) NOT NULL,
quantidadeMinima INT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY (idProduto),
CONSTRAINT FK_CATEGORIA_PRODUTO FOREIGN KEY (idCategoria) REFERENCES TB_CATEGORIAS(idCategoria)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT FK_FORNECEDOR_PRODUTO FOREIGN KEY (idFornecedor) REFERENCES TB_FORNECEDORES(idFornecedor)
ON DELETE NO ACTION
ON UPDATE CASCADE
);


CREATE TABLE TB_CLIENTES (
idCliente INT IDENTITY(1,1) NOT NULL,
nome VARCHAR(100) NOT NULL,
cpf VARCHAR(11) NOT NULL UNIQUE,
telefone VARCHAR(11) NOT NULL,
email varchar(255) NOT NULL UNIQUE,
sexo CHAR(1) NOT NULL,
dtCadastro DATETIME DEFAULT GETDATE(),
ativo BIT DEFAULT 1,
CONSTRAINT PK_CLIENTE PRIMARY KEY (idCliente)
);


CREATE TABLE TB_FORMASDEPAGAMENTOS (
idFormaDePagamento INT IDENTITY(1,1),
nomePagamento VARCHAR(50) NOT NULL,
descricao VARCHAR(255) NOT NULL,
taxaOperacao DEC(5,2) DEFAULT 0.00,
parcelasMaximas int default 1,
ativa bit DEFAULT 1,
aceitaPontos bit DEFAULT 0,
CONSTRAINT PK_FORMADEPAGAMENTO PRIMARY KEY (idFormaDePagamento)
);


CREATE TABLE TB_VENDAS (
idVenda INT IDENTITY(1,1) NOT NULL,
idCliente INT NOT NULL,
vlTotal dec(10,2) NOT NULL,
dtVenda DATETIME DEFAULT GETDATE(),
status VARCHAR(50) NOT NULL,
CONSTRAINT PK_VENDA PRIMARY KEY (idVenda),
CONSTRAINT FK_CLIENTE_VENDA FOREIGN KEY (idCliente) REFERENCES TB_CLIENTES(idCliente)
ON DELETE NO ACTION
ON UPDATE CASCADE
);

/*Armazena divisão de pagamento*/
CREATE TABLE TB_TIPODEPAGAMENTO (
idTipoDePagamento INT IDENTITY(1,1) NOT NULL,
idVenda INT NOT NULL ,
idFormaDePagamento INT NOT NULL,
valorPago DEC(10,2) NOT NULL,
CONSTRAINT PK_TIPODEPAGAMENTO PRIMARY KEY (idTipoDePagamento),
CONSTRAINT FK_VENDA_TIPO FOREIGN KEY (idVenda) REFERENCES TB_VENDAS(idVenda)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_FORMADEPAGAMENTO_TIPO FOREIGN KEY (idFormaDePagamento) REFERENCES TB_FORMASDEPAGAMENTOS(idFormaDePagamento)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE TB_ITENSVENDA (
idItemVenda INT IDENTITY(1,1) NOT NULL,
idProduto INT NOT NULL,
idVenda INT NOT NULL,
quantidade INT NOT NULL,
precoUnitario dec(10,2) NOT NULL,
subtotal dec(10,2) NOT NULL,
CONSTRAINT PK_ITEM PRIMARY KEY(idItemVenda),
CONSTRAINT FK_PRODUTO_ITEM FOREIGN KEY (idProduto) REFERENCES TB_PRODUTOS (idProduto)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT FK_VENDA_ITEM FOREIGN KEY(idVenda) REFERENCES TB_VENDAS(idVenda)
ON DELETE CASCADE
ON UPDATE CASCADE
);


CREATE TABLE TB_PROMOCOES(
idPromocao INT IDENTITY(1,1) NOT NULL,
nomePromocao VARCHAR(100) NOT NULL,
descricao VARCHAR(255) NOT NULL,
tipoPromocao VARCHAR(50) NOT NULL,
valorDesconto DEC(5,2) NULL,
percentualDesconto DEC(5,2) NULL,
dtInicio DATETIME NOT NULL,
dtFim DATETIME NOT NULL,
ativa BIT DEFAULT 1,
CONSTRAINT PK_PROMOCAO PRIMARY KEY (idPromocao)
);

CREATE TABLE TB_PRODUTOSPROMOCOES(
idProdutoPromocao INT IDENTITY(1,1) NOT NULL,
idPromocao INT NOT NULL,
idProduto INT NOT NULL,
precoPromocional DEC(10,2) NULL,
quantidadeMinima INT NULL,
/*Quantidade de produto que o cliente precisa levar para receber promocao*/
quantidadePague INT NULL,
CONSTRAINT PK_PRODUTOPROMOCAO PRIMARY KEY (idProdutoPromocao),
CONSTRAINT FK_PROMOCAO_PRODUTO FOREIGN KEY (idPromocao) REFERENCES TB_PROMOCOES(idPromocao)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT FK_PRODUTO_PROMOCAO FOREIGN KEY (idProduto) REFERENCES TB_PRODUTOS(idProduto)
ON DELETE NO ACTION
ON UPDATE CASCADE
);

CREATE TABLE TB_ESTOQUES(
idEstoque INT IDENTITY(1,1) NOT NULL,
idProduto INT NOT NULL,
quantidadeComprada INT NULL,
quantidadeAtual INT NULL,
dtValidade DATE NULL,
lote VARCHAR(255) NOT NULL,
dtEntrada DATE NOT NULL DEFAULT CAST(GETDATE()AS DATE),
precoCompra DEC(10,2) NOT NULL,
localizacao VARCHAR(100) NOT NULL,
CONSTRAINT PK_ESTOQUE PRIMARY KEY (idEstoque),
CONSTRAINT FK_PRODUTO_ESTOQUE FOREIGN KEY(idProduto) REFERENCES TB_PRODUTOS(idProduto)
ON DELETE NO ACTION 
ON UPDATE CASCADE
);

CREATE TABLE TB_PERMISSOES(
idPermissao INT IDENTITY(1,1) NOT NULL,
nomePerfil VARCHAR(100) NOT NULL,
descricao VARCHAR(100) NOT NULL,
/*VENDAS*/
podeVender BIT DEFAULT 1,
podeCancelarItens BIT DEFAULT 1,
podeCancelarVenda BIT DEFAULT 1,
podeAplicarDesconto BIT DEFAULT 1,
descontoMaximo BIT DEFAULT 1,
/*PRODUTOS*/
podeCadastrarProduto BIT DEFAULT 1,
podeEditarProduto BIT DEFAULT 1,
podeExcluirProduto BIT DEFAULT 1,
/*ESTOQUE*/
podeGerenciarEstoque BIT DEFAULT 1,
podeAjustarEstoque BIT DEFAULT 1,
/*CLIENTES*/
podeCadastrarCliente BIT DEFAULT 1,
podeEditarCliente BIT DEFAULT 1,
podeVisualizarCliente BIT DEFAULT 1,
/*FINANCEIRO*/
podeVisualizarRelatorios BIT DEFAULT 1,
podeVisualizarVisualizarFaturamento BIT DEFAULT 1,
podeAbrirCaixa BIT DEFAULT 1,
podeFecharCaixa BIT DEFAULT 1,
/*ADMINISTRATIVO*/
podeGerenciarUsuarios BIT DEFAULT 1,
podeGerenciarPermissoes BIT DEFAULT 1,
podeAcessarConfigSistema BIT DEFAULT 1,
ativa BIT DEFAULT 1,
CONSTRAINT PK_PERMISSSAO PRIMARY KEY (idPermissao)
);

CREATE TABLE TB_USUARIOS(
idUsuario INT IDENTITY(1,1) NOT NULL,
idPermissao INT NOT NULL,
nome VARCHAR(255) NOT NULL,
cpf VARCHAR(11) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
dtCadastro DATE DEFAULT CAST(GETDATE() AS DATE),
dtUltimoAcesso DATE DEFAULT CAST(GETDATE() AS DATE),
senha VARCHAR(255) NOT NULL,
ativa BIT DEFAULT 1 NOT NULL,
tentativasLogin INT NULL,
bloqueadoAte INT DEFAULT 3,
CONSTRAINT PK_USUARIO PRIMARY KEY (idUsuario),
CONSTRAINT FK_PERMISSAO_USUARIO FOREIGN KEY (idPermissao) REFERENCES TB_PERMISSOES(idPermissao)
ON DELETE NO ACTION
ON UPDATE CASCADE
);

CREATE TABLE TB_MOVIMENTACAOESTOQUE(
idMovimentacao INT IDENTITY(1,1) NOT NULL,
idProduto INT NOT NULL,
idEstoque INT NOT NULL,
idVenda INT NOT NULL,
idUsuario INT NOT NULL,
tipoMovimentacao VARCHAR(50) NOT NULL,
motivo varchar(100) NOT NULL,
quantidade INT NULL,
dtMovimentacao DATE DEFAULT CAST(GETDATE() AS DATE),
CONSTRAINT PK_MOVIMENTACAO PRIMARY KEY (idMovimentacao),
CONSTRAINT FK_PRODUTO_MOVIMENTACAO FOREIGN KEY (idProduto) REFERENCES TB_PRODUTOS(idProduto)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT FK_ESTOQUE_MOVIMENTACAO FOREIGN KEY (idEstoque) REFERENCES TB_ESTOQUES(idEstoque)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT FK_VENDA_MOVIMENTACAO FOREIGN KEY (idVenda) REFERENCES TB_VENDAS(idVenda)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_USUARIO_MOVIMENTACAO FOREIGN KEY (idUsuario) REFERENCES TB_USUARIOS(idUsuario)
ON DELETE NO ACTION
ON UPDATE CASCADE
);

CREATE TABLE TB_CARTAOFIDELIDADE (
idCartao INT IDENTITY(1,1) NOT NULL,
idCliente INT NOT NULL,
pontos INT NULL,
pontosAcumulado INT NULL,
dtCadastro DATE NOT NULL,
dtUltimaMovimentacao DATE NOT NULL,
statusCartao VARCHAR(100) NOT NULL,
NivelFidelidade VARCHAR(100) NOT NULL,
CONSTRAINT PK_CARTAO PRIMARY KEY (idCartao),
CONSTRAINT FK_CLIENTE_CARTAO FOREIGN KEY (idCliente) REFERENCES TB_CLIENTES (idCliente)
ON DELETE NO ACTION 
ON UPDATE CASCADE
);

CREATE TABLE TB_MOVIMENTACAOCARTAO(
idMoviCartao INT IDENTITY(1,1) NOT NULL,
idCartao INT NOT NULL,
idVenda INT NOT NULL,
tipoMoviCartao VARCHAR(100) NOT NULL,
pontos INT NULL,
dtMovimentacao DATE NOT NULL,
descricao VARCHAR(255) NOT NULL,
dtExpiracao DATE NOT NULL,
CONSTRAINT PK_MOVICARTAO PRIMARY KEY (idMoviCartao),
CONSTRAINT FK_CARTAO_MOVICARTAO FOREIGN KEY (idCartao) REFERENCES TB_CARTAOFIDELIDADE(idCartao)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT FK_VENDA_MOVICARTAO FOREIGN KEY (idVenda) REFERENCES TB_VENDAS(idVenda)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

CREATE TABLE TB_REGRASPONTUACOES(
idRegra INT IDENTITY(1,1) NOT NULL,
idProduto INT NOT NULL,
nomeRegra VARCHAR(100) NOT NULL,
tipoRegra VARCHAR(100) NOT NULL,
valorMinimo DEC(10,2) NULL,
pontosGanhos DEC(10,2) NULL,
multiplicador DEC(6,4) NULL,
categoria VARCHAR(100) NOT NULL,
diaSemana VARCHAR(100) NULL,
dtInicio DATE NOT NULL,
dtFim DATE NULL,
ativa BIT DEFAULT 1,
CONSTRAINT PK_REGRA PRIMARY KEY(idRegra),
CONSTRAINT FK_PRODUTO_REGRA FOREIGN KEY(idProduto) REFERENCES TB_PRODUTOS (idProduto)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT CK_PONTUACAO_DEFINIDA CHECK 
(
	pontosGanhos IS NOT NULL OR multiplicador IS NOT NULL
)
);

CREATE TABLE TB_RESGATES(
idResgate INT IDENTITY(1,1) NOT NULL,
idProduto INT NOT NULL,
nomeResgate VARCHAR(100) NOT NULL,
descricao VARCHAR(255) NOT NULL,
pontosNecessarios INT NOT NULL,
tipoResgate VARCHAR(100) NULL,
valorDesconto DEC(10,2) NULL,
estoqueDisponiveis INT NULL,
dtValidade DATE NULL,
ativo BIT DEFAULT 1,
CONSTRAINT PK_RESGATE PRIMARY KEY (idResgate),
CONSTRAINT FK_PRODUTO_RESGATE FOREIGN KEY (idProduto) REFERENCES TB_PRODUTOS (idProduto)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT CK_PONTOS_RESGATE_VALIDO CHECK (pontosNecessarios > 0)
);

CREATE TABLE TB_HISTORICORESGATE(
idHistorico INT IDENTITY(1,1) NOT NULL,
idCartao INT NOT NULL,
idResgate INT NOT NULL,
idVenda INT NOT NULL,
pontosUtilizados INT NULL,
dtResgate DATE NULL,
statusResgate VARCHAR(100) NOT NULL,
CONSTRAINT PK_HISTORICORESGATE PRIMARY KEY (idHistorico),
CONSTRAINT FK_CARTAO_HISTORICO FOREIGN KEY (idCartao) REFERENCES TB_CARTAOFIDELIDADE (idCartao)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT FK_RESGATE_HISTORICO FOREIGN KEY (idResgate) REFERENCES TB_RESGATES(idResgate)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT FK_VENDA_HISTORICORESGATE  FOREIGN KEY(idVenda) REFERENCES TB_VENDAS (idVenda)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

