CREATE DATABASE SysB;
Use SysB;


CREATE TABLE TB_CATEGORIAS(
idCategoria INT IDENTITY(1,1) NOT NULL,
NOME VARCHAR(100) NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY (idCategoria)
);

CREATE TABLE TB_FORNECEDORES(
idFornecedor INT IDENTITY(1,1) NOT NULL,
nome VARCHAR(100) NOT NULL,
cnpj VARCHAR(15) NOT NULL,
telefone VARCHAR(11) NOT NULL,
dtContrato DATE NOT NULL,
ativo bit DEFAULT 1,
CONSTRAINT PK_FORNECEDOR PRIMARY KEY (idFornecedor)
);


CREATE TABLE TB_PRODUTOS (
idProduto INT IDENTITY(1,1) NOT NULL,
idCategoria INT NOT NULL,
idFornecedor INT NOT NULL,
nome VARCHAR(100) NOT NULL,
descricao varchar(255) NOT NULL,
valor DEC(10,2) NOT NULL,
codigoDeBarra VARCHAR(255) NOT NULL,
Marca varchar(100) NOT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY (idProduto),
CONSTRAINT FK_CATEGORIA_PRODUTO FOREIGN KEY (idCategoria) REFERENCES TB_CATEGORIAS(idCategoria)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT FK_FORNECEDOR_PRODUTO FOREIGN KEY (idFornecedor) REFERENCES TB_FORNECEDORES(idFornecedor)
ON DELETE NO ACTION
ON UPDATE CASCADE
);

